@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@email = test16@example.com
@password = Test123!@$
@username = eestuser16
@name = Test User 14

### Sign Up - Valid Input
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "username": "{{username}}",
    "password": "{{password}}",
    "name": "{{name}}",
    "academicNumber": 123456789,
    "department": "IT",
    "studyLevel": 2
}


### Sign Up - Existing User (Should Fail)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "username": "testuser2",
    "password": "{{password}}",
    "name": "Test User 2"
}