@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

### Debug - Get Refresh Tokens
GET {{baseUrl}}/auth/debug/tokens
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NDAzMjMyNDMsImV4cCI6MTc0MDMyNDE0M30.orbo77fDIWm0zAADQEljeuZ7H3zM_ZEPE42DKi8QUmoMwxjPIzakjGBQVGvoXKblbiWb8C8mveFJc1opWVwOJWA4VdVX-WW5XXvy2u8Au384jAdBCMcQ4rLd3KbBHOOvZtXW1AkZLaGM8nOtG2GueLyIQDW-63qSytgUQrQliHMX3PMhbvMQmcI1b5FLvXtL4SfEW6z3VZ-ZwX-RNmk-Nay_B68R5rGHXUp824JZnihgYMFoiMwgCWLEz_UNGPEnxSOSGHBNlwTQ04rimM70-OjyCliVA8yWiB9ZOJxK_IVY2LZi09Nfy45N0cH5BhldmvfGVVrHujTizGT6SyUJ3A