@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@email = test1ss3@example.com
@password = Test123!@$
@username = test_user3
@name = Test User

### Sign Up - Valid Input
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "username": "{{username}}",
    "name": "{{name}}",
    "academicNumber": "1299567589126",
    "department": "IT",
    "studyLevel": 2
}


### Sign Up - Existing User (Should Fail)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "username": "testuser2",
    "password": "{{password}}",
    "name": "Test User 2"
}