@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@username = test_user_new_3
@password = Test$1234
@academicNumber = 1299569589193
@name = Test User 3

### Sign Up - Valid Student Input (EMAIL_PASSWORD)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}",
    "name": "{{name}}",
    "academicNumber": "{{academicNumber}}",
    "department": "IT",
    "studyLevel": 2
}