@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@username = test_user_new_
@password = Test$1234
@academicNumber = 1299569589195
@adminUsername = {{$dotenv SUPER_ADMIN_USERNAME}}
@adminPassword = {{$dotenv SUPER_ADMIN_PASSWORD}}

### Sign In - Student with Username
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "identifier": "{{adminUsername}}",
    "password": "{{adminPassword}}"
}

### Sign In - Admin with Username
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "identifier": "{{adminUsername}}",
    "password": "{{adminPassword}}"
}