@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@email = test15@example.com
@password = Test123!@#
@adminEmail = {{$dotenv SUPER_ADMIN_EMAIL}}
@adminPassword = {{$dotenv SUPER_ADMIN_PASSWORD}}

### Sign In - Valid Credentials
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}

### Sign In - Invalid Password
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "wrongpassword"
}

### Sign In - Non-existent User
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "nonexistent@example.com",
    "password": "{{password}}"
}