@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@email = test@example.com
@password = Test123!@#

### Sign Out - Valid Token
# Replace the following placeholders with actual values:
# 1. accessToken: Replace with the access token received after signing in
# 2. refreshToken: Replace with the refresh token from the signin response
# Note: Only include the refresh token value up to the "Expires" parameter
# If you encounter issues, try removing the "Max-Age"
# e.g: Cookie: refreshToken=eyJ..Ig; Path=/auth/; Expires=Fri, 07 Mar 2025 23:10:52 GMT;
POST {{baseUrl}}/auth/signout
Authorization: Bearer accessToken
Cookie: refreshToken
Content-Type: application/json

### Sign Out - Invalid Access Token (Should Fail)
POST {{baseUrl}}/auth/signout
Authorization: Bearer invalid_token
Cookie: refreshToken
Content-Type: application/json

### Sign Out - No Refresh Token Cookie (Should Fail)
# Clear your cookies before running this test
POST {{baseUrl}}/auth/signout
Authorization: Bearer accessToken
Content-Type: application/json