@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@email = test@example.com
@password = Test123!@#

### Sign Out - Valid Token
# Replace the following placeholders with actual values:
# 1. accessToken: Replace with the access token received after signing in
# 2. refreshToken: Replace with the refresh token from the signin response
# Note: Only include the refresh token value up to the "Expires" parameter
# If you encounter issues, try removing the "Max-Age"
# e.g: Cookie: refreshToken=eyJ..Ig; Path=/auth/; Expires=Fri, 07 Mar 2025 23:10:52 GMT;
POST {{baseUrl}}/auth/signout
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjIzMDA1OSwiZXhwIjoxNzQ2MjMwOTU5fQ.TIttZqpvquMFYWdAsjZnZNpjw0zCorQs0-pgOBe2PddSROw71fmoMmA_nM6dFRW6V2lA8znyvScjqY7z_FPb2PX-c-FbZPzKWfrY_I7fKg-_xcuhYkfV8-zEST5_jw8S1_Wfit0wNCdeso7mpt__msoJjYf0_jhPZ0LdTET3MBkUO1RGgbmPGiq4iRdrc7QTfnPyCJLi0k2BPgfpmuhcsTTq5QMHIWYBn26sNtJfhtPMt2EkQOPQa1vSSBUN3SmIa-Aybx5QhRAFa6HsfJck9qCp6isCFbMKCkwki2blOG6B8x39-lL7iQkAE_N1RoSrxHR9WaaLEuW6g40fUDVrjBcgkxgHaNNZrbuZYANo067F6jmwPuGH5SHK_A2C1PlswVh52oC1NYIXQiAMmsE0Ic7JPOYGTEQxQyBRQX7hT_79axRqgRSMv9iFx6NRSUywy-508sJj69_1RVEkL5AKGZ0vLCYTMp9oP_70F1-T9qrjYqzuOPyTlMLFvxqnQa6wMfmFKbCXKgtzRnin3FihGuqDvril--VMlXZIpU3lSarhs7EkKIOKVnBZ8fbA-4jAs7ElFrsJLPsglbBjv3iQD234i6OVcdNdVVo79U27ZieLA7yzkv4PXsW_WzEK-zSahwrCP1KVcQ7sBGUcr0mfkmKibzGV5nWRfHYzfhQp9AM
Cookie: refreshToken=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6InJlZnJlc2giLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NDYyMzAwNTksImV4cCI6MTc0NjgzNDg1OX0.qOU2u9plFuvOz9Cx3Ufb9-2VHQ4HJAeZjwn3289m_9ctj0tYCqn764Gqbx-pV7iEd5XG2qhAoNJ-qoWwdzL_E1K0jqwt8ElRM_UjjHAw3ncq3p8bb8tuHBLvv-rTkZhRMztJPIMbPvjN5ld8QDNUJTLGP2A9tYHiSpdlxyh8lyEQcHCST6s7hMS6ims2it0G0oRm-3-3-e1G-jRNC4EKNbBcV9Bob4rRePY6K5cGtfintXBQbeBMR7IS4ja_-oO3OUCYIRPO6-sUrW0J-cLtyk3qYynKjaiXSekx5qNqeWrYuHRN9a9NVZEVfTTfyoFD6TO9nHBzUbtb7D-0ls1RaS4SFznsHz96g2lOiWn4pkLeYRsEXxLCHQ807tFvSbtIJj8JRLdJ0sN7ZQwu2U49lC4mn_1zRIGM5qKh4IbTWNc8ry-9Zstm-HihTvGD7zn6BV30kJP-qsaA4sVppbvn8fxLCqbF3kTkbsiLQHyVu2jl_z12WFT8XLyui7aLUUlNh4Ouv4tyWU-vmL6IG-vei5lxYFGmq5OWALeEmsJ8VhCpkbOhFhP81AkCzGizt-aO-AvnYuDlQAxYfqKyBE_OhThdL9Ocv7FlZ6_h5vCxK3j8zFEJ9P0YRQLedtfpc22vQXNsQzPsNPd8LPaUBeX-KHKnhz-QBQ7zu5jhn_ZHxbI; Max-Age=604800; Path=/auth/; Expires=Fri, 09 May 2025 23:54:20 GMT; HttpOnly; SameSite=Lax
Content-Type: application/json

### Sign Out - Invalid Access Token (Should Fail)
POST {{baseUrl}}/auth/signout
Authorization: Bearer invalid_token
Cookie: refreshToken
Content-Type: application/json

### Sign Out - No Refresh Token Cookie (Should Fail)
# Clear your cookies before running this test
POST {{baseUrl}}/auth/signout
Authorization: Bearer accessToken
Content-Type: application/json