@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = 

@newName = Super Admin


### Test Approved Student Access
PATCH  {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{newName}}",
    "photoPath": "invalid path"
}