@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0Njg5Mjc5OCwiZXhwIjoxNzQ2ODkzNjk4fQ.peMjpC5O4UDyFSpoNbzMmMpxhrAkZu_RrS3nw2CtJLI_fURZqrT4UvnNBNHRobeisEmx5E2J9T4JuMnhn1YJUoy1FZGdZuSbKy0eJTvjsamjO3EMqEf6sCGZ0kFxwKOoojUp7hmtMSnQK2C7_KFMf7IFkO-61FyZqMXAxPRxFOaUt2o1hPErqZJ5UVjY39Mr68ujXY7_eTKiPuY-hDLvJmbgsS3r7FHyXAu5ql2qypsXrQFhbXZupCWGNOBFk9Cl0n7GFpAFPG15QCq0BGQB2ty2hELXLSl-2W_KBnepge2g_9uEbNNkN2A6HbaYTqgNmrScOiPPKVsR3qP--b5Av4jKXL4c8JJ1JAfPGwKKkzDKTNtvPVwd2gUF4eWYXzKYZUgLNHEoLGCpH_wVzQ1XV34KgIgyLOrdn5ClTfWhJNys385F3Ww_X6GYcb2KXcTb9q0WrBC640I1tMUfclDQm_5dH8E8igkvdnIowjmiU580FQm5sxUJmk6XttpW_HATJnMNUDwGvC5uZ5PbMjgTHvlFDBqjVcCh3MuW_o3PdzkbmJdgCRmTv7oLaPliR9uHl_LZ6XS8QGcNCQkKs7Ob3bAql9vIFsc07d7DsmhQNm1-rD_mOoSBWhmYwMOpAp3LiTSQGPf2s5bmAJ91Mhsb9baMoyxEabZlnhMDugqq-KM
@username = 

### Test Approved Student Access
GET {{baseUrl}}/users/{{username}}?includeThreads=true&page=1&limit=5&search=
Authorization: Bearer {{accessToken}}