@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NDM2MzIyMDAsImV4cCI6MTc0MzYzMzEwMH0.j-h7UZjk4pvZpBFHuufaK5lk0yqb7jp_JhfSxAHDevRXhoFKgFoNWhHPRq9tVX-FqAJcvhpXUd9w0cJr6tFnr6phfQPbw6ZqPFPaNsjT0dBssPaeUpYfxwEUwcMxuZ-8l1uH02oPnDxr4LeRlgz-hi-D_mqIxwI0lJNCd8Hb6UwClaD9VaRq8Q-warPLGg8U9EagdptWqTHq0rzJevHHbWNTwdMOy1b6UhngO4MBgE2SChT-KcguxIeJequQE-rP0vJAO68kmHNichWEQNh7S3miFrAKd5HQSCdTVw63XZVmXEDe5lrd6LP-qOqr0yPnGadGCk6jkd4PblZaLP5_cMYafF7CKPbijNdLk9-hPQHUkhBOZH9sgMjEg61URRKiLvRGuZDzZNDR-CSuegqqOuBfj44z5yO6nEsu2FiyvH0tehI64wBhYNiM38kvzdVcu_HMnL5r1V4C4I3-SlsEr5mi7O29IsuSQufX4GGH44ggkoT-lvRjDI-YhJ_Zq0dhou6AF_b-Z7gl2GEIFf8wAVT8PrRM4WRuyu9e-s0eE2UxDxYZrUruBXmOPy24vFMVgLgEPKdqaI9HWXpqAZ1yR4ruCJbnM7YUeVF7r55dOiAcYcS0KBR1ijQtLB1mxPWaWLIV3Her3OgZDsGM-BqFUEKZ0TYVZnozsu6XWNzVU4o

### Test Approved Student Access
GET {{baseUrl}}/users/test-approved-student
Authorization: Bearer {{accessToken}}
