services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sahim
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sahim"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: