@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDI2MTExOSwiZXhwIjoxNzQ0MjYyMDE5fQ.SvQM2vP4rvUao7IQIodvvsjHO4fX7Aj6YL_ZhmxV4ZsWsmejLkH7JjxdqdD7_a0muBX5eezzTzpPoVl0DimTeeZkaccfA5gn8F9kktAblB-H13jAhe8GqTMGpsWReRUE-lWs4wx5es5jNohMwHV1l7DN88Kr0PNFXqra13XRQcTKzo0TrPr8-Nu3Uhv8hBf67h4QWUyaoLrTN0yBR_D83nDQ5OtXGlaVau1FTc1XSQ3jJDtCY_2spIi_0dHCcb_fzCoDYi84wepKmElVjKdVKEe-TCmPcc9nWXgHG2gGzbiuMNqt3cVxwbIdEJFmXLf_4yPno03VpvczFs-B2ETldQ8S2Ma-Wjotkl7ZNsuEb0F69cLihy5L9mN8CKrv1tIF-6mWqqg8lseL7Gl8T3PrAwlq7pkOQ-VC7Lqo_EOgmFKGiY9U3X1VjUDLkqSV_sqA-XG5q2TQj4fVMP0MIT7OmE05fvkYm7NBeItIqFSXaUUjEkRwFQqp3gwijtvTzMXYlD-SJRJUg3jFn7Zdd0HM4romRv0RUf2ELJU99R3UsDszSUcQTJBH36PwW6sq9cn48GH1qC8vjM9Uvc1Jz1pxMYXJdYNQlrOAEGc8IpMnqK3PI0Rm8qM2yokdB95E4dS4qxNU48DXhggcKvJb7HLyh3rg4xIb7_EoA_2oxz1dFG8

GET {{baseUrl}}/admins/users/students?status=PENDING
Authorization: Bearer {{accessToken}}
Content-Type: application/json