@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

@accessToken =  eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NTAyMzgyMSwiZXhwIjoxNzQ1MDI0NzIxfQ.Zuxau6k1xYIo-Tu0xTAUXnwFV6KgbM_rTElqpWM_IVdfM4o2rVi4LDHCx3NXKUcKg711xt9xkZSfnFnEL_-KClxPxatvEVhDJpl6U-7DWUhfk5DhcDMUutFYjf6xROGMEs8ELNo2c4Rrw3dL1rwjgItKg6iJu8DAdbMW4iGKcK7hciF-1BiQ77LIMHe8kvX2lV7wWLT_wTI13hmUDjhFxTzmBKImR1JoRwSX_d_nqnnBe0nZ5iv7t_Ivv7FrRLIs0cPXgZuo6q03Wif4pNy5Er0hW0CigBXp12dIaPBCxSPYYlVFzQqmLWJ4IbIbiv62dCeauDfKORDgPFAbB1sstD2UjcZV68QxnIA4103_-WmuDUmPjvCbqGiHw9QASY84jWp8xUEd7AXhDQgWYomXjRnoigXKNRn40CVqZV-rgIaiFuD64VuTP9GN0s8TOHZdLL7da_XHix7-CP8FVk3bu1S0LLm1158IZTf5S5Q78x696CcwESYT3_pZLdCgZ9WmbH4jwPrH4AiMeoO55zAZFcaVe03f7n6jvYzhEURL6QFT_KEfLpM39V6p7khEgjcQhTz5uFl72mcdBVpBRPFQ01TYbF1PTBm3cYv0bbRRimeqMvt0Eh7NUVBmwO-NUQqekNfXESxg4EGoFsF3sVmxZgDrtaMlWfg5MZmC6vLAc_E

@updatedCategoryName = Updated Category
@categoryName = Test Category 1
@categoryId = 4  

### Create Category
POST {{baseUrl}}/admins/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{categoryName}}"
}

### Delete Category
DELETE {{baseUrl}}/admins/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}

### Update Category
PATCH {{baseUrl}}/admins/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{updatedCategoryName}}"
}