@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@adminId = 3

### delete admin as super admin
DELETE {{baseUrl}}/admins/{{adminId}}
Authorization: Bearer accessToken

### self delete admin
DELETE {{baseUrl}}/admins/{{adminId}}
Authorization: Bearer accessToken

### delete super admin (will fail)
DELETE {{baseUrl}}/admins/{{adminId}}
Authorization: Bearer accessToken

### delete other admin as a regular admin (will fail)
DELETE {{baseUrl}}/admins/{{adminId}}
Authorization: Bearer accessToken