@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDMzMjk0MCwiZXhwIjoxNzQ0MzMzODQwfQ.LyEK7BlZKWUP5t0yHKDcfXTM3_P6YSRvtIsBHxbTRBgtZxi_UMzol24z9--dJT57pIl2u0RJ2Usj5BXV5Kugyw4T2gLxm9dOccdiDocN4GvnNa03nyhk_X0O8DMtzjBV3tbBRThKOzne8BmRmJiQxPZHvZvw7rT-M_KWTkhliXll9vDVwJt7ZSyQFHMw9HPE5gGZfVwEuXJJZF-eO-DQySLv6ZUzzKUT5A80aNh1dwCxSJ3OTsf81EPjgNQEJktVBH7swZ-8ld2dIBESiDmqt78Sn0eoL349guZNG5C-MIurZ8jKitVQj-jTa9ZzfIM7wFR0itIyQggeCjMRLESzNmoADoLEq3DbLzHqFEfdZgMgFxl4Cl_hXoMu21Wj0c6QtOke0HPyosA31FnDX8pZBkkh8uctNz8awQXSUrf0rzw_xImwv5BB3sHiPN4UAq1Wo-uz5Um31MXfQ5a3oEMXfb2_Z-dwRVMYmfnMnuY3rwHnnEH0fxA3JXicFcclVTUMsqvncG8S0D9oeODYFerchj1CvOPVcksR_p2AMUSsluGm8AY8Bj8JdFW3VCqrNrHRAK5rLKl4s41DyNq1WqGWgefE2UT_pMoMu7HB_RL4jfdUtMYsEv6Sy2fn27EETJqpVDcCCNC4h8G8YNaoIBJmBixvhA4F2U-hjmAPHjIdiEI

@query = 234

GET {{baseUrl}}/admins/users/students/search?query={{query}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json