@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@studentId = 2
@accessToken = 

### Reject Student
PATCH {{baseUrl}}/admins/students/{{studentId}}/reject
Authorization: Bearer {{accessToken}}
Content-Type: application/json 