@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

@accessToken =  eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjczNTczMywiZXhwIjoxNzQ2NzM2NjMzfQ.MQri0LdasoWbFLZimR1Ojst_4QA7gVxIEt-NuJMuw1MxN4qTQfueUOA1do2fjc3INkUMh_7_E6pMQFXorOhD9hD6TOjvfQlvXJVX7xMSmwsTr5sv1inDdbF-9K1APgdNWE31wfi862OsdanC1iViWBePOEHgtBGGjG7Rjb5isMmliz4xOYShqTYA4Y7ych6djfFMj35UY7WO04ih0E6fXx3dwJngl-m03XaDY5dLp0msJTUVSgy46PdnxKhEe29m9FqT_x21pJZ7fCwGiWwwXjz3tGmnfAsq6HuGFrLQyuNF423A8dkBN0_h1WxBhaLndOGHizVHSHyP8_L0S3t_sUta-PcFv2wt56ROJZ9INSAsSfnf1VX0-CX_NoJVrIzJpoyPqfsTrUtQMF8p5g7C1M9cd5Uyjv7hMPzG8NW28VRTHl0ZjMqb-mlH0T7Q7eXh_mlZx6vquQpcgmGAbIUArwj3_n3fdQd2oAkad2DjPay_xko3cint1dusBsEPboDl7RsckJX9u-s839PPVaC3RaSMHUoSW6NJsNBO0edC-UQr1dGVo4vGhnuGwzy9U1DS_dUmIxKPmPHduZ-XgO12mR_NdyaXUlxH515x2J6ADTkqXx_hiRKkClrqz8guarRDa7eO1p53BDka_WWC5GZHAhxM47jgDDdCafgOfgE5oV8

@updatedCategoryName = Updated Category
@categoryName = <script>alert('hack')</script>SafeNam
@categoryId = 4  

### Create Category
POST {{baseUrl}}/admins/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{categoryName}}"
}

### Delete Category
DELETE {{baseUrl}}/admins/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}

### Update Category
PATCH {{baseUrl}}/admins/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{updatedCategoryName}}"
}