@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = 

@query = 234

@status = PENDING

GET {{baseUrl}}/admins/users/students/search?query={{query}}&status={{status}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json