GET http://localhost:5000/admins
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzQ0NTc0NTMwLCJleHAiOjE3NDQ1NzU0MzB9.hvYHgTQ7EmuwFxd4bAM7nCgA_SZiJ5SbMDvVBFAAvpEpQQkHhHYDv2eNRVFcmYJp8THFWPz4F-pXsFIuUU575KXgk18hTfjy5KO0F4oTMy_9C4ZVd4Nh1UqOerlgy7OGfQlkImFDx-2JfKOK9nB2_6vGWyU_j9tISA3UYBMZEB1HQBQYiQuhYXzsXVVJfPRiZp8k9nCAJRGItEcDSW4u6oVCFiY2w6LsIdbLfxIOZv7KKsN-Ed_oMhpd2aOHZygJ0aDbeDka8rk4gQOEJcOD1paODSLIufQEMjC1doYobCpAm967RIzEYVpYfVlhutFoZ6cjc-OkWTtd9uy7QB5tP-YLPawo9-8n93TgpBnHZ_Lrb2JA48pYgAP-zUKYlOv7B2njkcPnfQGiuSPoOJ5ouPdwf1HcJ3fTRDMMGUZoM3CrBrV3C2r_kiWAABCOv5hx89xM7CFWzwkDgDO4i1CpacRto8-kVLG1ZKv8WhsqcK1aTrlBjIUaoRye4v0zVpGXHYJPRM8iALMJ3isRTgXctO9vK5VeY-clmV5yuLBvUT2wpmB7zl5LAp036cUUUlX0UzjV8d6x3F4g7aJQKWrGb-rcB-lJYkQdlRaXluinMSn0lPz1m_qP6eU4L-O1jmqHhA3EmCKShABB0nBarxAO5ktmT7ns3aGRt5IlJHzXEeo