@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjgwMTE1OCwiZXhwIjoxNzQ2ODAyMDU4fQ.ZaDdDMtQ6shAwMjJOFHD3IFUEr0AMe9wcH0UJcpCvp1Gq-fBLQPHBEUzH-_S1u_xTL0b8D8rycyKLEPPt35H1m4gNsXDMukoOntzoHIXTn_8VJEHKrh6qjLqR8cX4Nnt8X7cmHz7bcU87N442IGs3wt9y1W9TcvtMAgs__Z-wjaYDW48_8emTroBjU1QUZ5eqOn11F8xfAsWF64GcH6C53Za9IOywROvK2gO9ecnagY7QtfEXzNHUi4UVKzioFaucQoeyRc4Un9kZIbeEI0q36-6WkjwALpzIlawyE6FM5GiNCT6HaL-YjObrM8styz1s-85T8klNniHbT9369420PPyNs5t8cuyQmvkGVyGeW0VPPQl3iBr55VINexnhhvQx3zynokDY795xBrMdpHJlK6zKIdUihNicdrbaL9uZsbECPINoy4Hm_oyxmMnOCttgQYt4JmE2bHncvtNci4SXHx3gFKhX73anJfdtYQakhHDCTjVLA4O6T_OuWkgDPCCRyBOuV5sU5NKB_4jQ3cn-Bdx_ebiY1rHshXChG5bbQQ8980-x7snqT0qybCHy9GFYMI8zFNuN7R1zZRtW9omGwd6zjh3hnFeRwiE68qh_UrDPmO4J9XCY5K633mVgL3xGwT4m2TmWTTAhAExAbMjbL8FKejM705mUljItKBl0aI

GET {{baseUrl}}/admins/users/students?search=محمد
Authorization: Bearer {{accessToken}}
Content-Type: application/json