GET http://localhost:5000/admins
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjQwNzIxNywiZXhwIjoxNzQ2NDA4MTE3fQ.bY6kywrEoswCdAH77a22FPW2SOcaMRtdLqPxdBMYZmYuNu0U3i2EKNd46vUuDXk9DkYXfk5-p0E2-Qx8GMSJFFEpvHI6hL3v1NQQ8valCfI-vgNkWLT7WQT1Q_BDj0JXXCVmH8e2hPKs8f5kbAbbHTpuaKPLT4AGVmpGEDE8v2jBk3ggeNX9yJ5kroZxLKlacDJj5zDwmI9eajLubfSmWFHE5_yh9kO_V5hTVStVInEmwPfavcAMZO3Tme-IzCTMDjqvMhpw1bj3XvqgmTJVa3YSedgjOHj9eCjrww8oBbAyMCgyCSmN2GXVTObcaTxQg-D-awEvpELHVBqcnh1_-RU3uOS4bnGFzEIO3mVRHLWRV2RiGU9vvgBtnfLE4eU3nyA8bn1zYsOUkC_7BxCAHkjHNa-3Yp5dNt1BbwSEOgSCe45gsOVyCY07wgFXunD3BSXcBUshdIx0bBRXImNLQy4HzwmEjdUtuJ1DZy5NTJovRktq7gtdZmXRN3O9Y7sN1b8TURXKtaraJGai0EB1glbouDPpokVLJxAq_7dnF9DutarAbBIKsErqDWfccEwmCAbmk6kLQLP9DpbfvNn5SEG5zP0i34csr94p-1H9o4Dk8Vxrcl-1qcI_1CYkujcbNKYuaYTR2Gx3C4eEB9PfJ8nRrW56u7C7LdnOf19zPjE