@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjQxMDc3OSwiZXhwIjoxNzQ2NDExNjc5fQ.OWcTJMj_Ivzh1idaFR0pa41Sg1pILcF4JDOKLdqbXKrhwZgG58uamTgjpFW2btOddDIqJDIIZsKcAdRv7VgpSf3_qKHCNPjtMf1GmzbOYL8Qhy7MbFaCUvoyMvjYKqJsdRO2mcLabqV6LJfjg-7wY7WnmYZ07-nj3AWe9eyGlAH8da3zeTQKu0eHqtDWf7Tz5vKVlRGaHJiXSIva0vJpoi8zoWlurhWKqhpnANECu1_A4NQt3z--HyLYCGBk8Kd-MyxpW-BfXCFQ5LQ0RONqKu6C4emrVDiLXHPN8PQgBQzv4oDQVu9Fx1AgV6DJdkR-1RJ1aFmE9NXOWTcItgno1grX3ig4dh2837L6_ejGs5eJNvkKAbIvYSZWv8Kv9axByMCEmMn9YpVqvuDGZf_Sl5pW7o7mP5tKqU0k6-hk-icezbilZ9gquS2y2Aj9siftbHEEhvvwm-qfrN-TYtk5pacHtJepuiNS40ZFbi1GmorZlCKy_it9mHC73jvR1mTs4y3gs0ePb7JrctqFslaJ2BTnd0vbEBXK5FES_tmY-ZMcBgs4QcOtGXNR1ymyEVW-QtPD5IwQbHJgiryj-VQgcQBte0t3_rTkneSCSJrLiFyqN3NysqBBGsJNsdtBJtepMMyKQ7vvZQ-xUpUuShgjmLtgYtN1QOtKfv6cwiXRqGs

GET {{baseUrl}}/admins/users/students?searchTerm=a
Authorization: Bearer {{accessToken}}
Content-Type: application/json