@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NDM3MzYyNTUsImV4cCI6MTc0MzczNzE1NX0.GvH4gpHaqiZ5_qiQTbhfItejenKKnP_FkjTpo0Ub5yKwJkmBUVMqm3PIZeuDWSZV0JWDclF0ywiwZ2bFWkbQN27rj1ZFFYC-icuuR_iSMSWxWBN2rs-q2i-87JQHREketwKTmj2U7RHtldlgWQsSkCt9j8lD71MQDvcFZ4PW5SLRQ6t5lrzPuWWo27jAvGG63_sndhGzFSncm7PqMV3ss8tKhiQOWtbzQAjEWU78ywHemL8QQAc0FknQvvTWpWYUoVxVHK_pymAEzfRfc0TI29aZTdiMH09OCkX5DbBWqurIHCWBcjPV6zBMZoBXnuojOoON5kD9e4AGOnCTdji7vaT4xDShbXB6VIGsoCiwBMLY6xZXH5iCWl9oDs8PK3D-zkTqw32gh6YaW3OWNdlS5AupzbzAZDJnFTyndRHndkdkJmIR79WxlfWFeE7T-rD2H69a9CFXZOE0PSyloxxdO-eAFiRV5uRFtPEgC7b8UBkKeVWUBwjzXJDizfnuA-R_bEg6qKL4a55LP5dL5TvWHVgLQeKYUaWyep5H9pEjezispzfRn2N8GYDqJmvEmSJluBlrh-YrNZV94PBAn0vJHG357kCQ2pFr8SqBfKrjXqwKBuTj9XWKOk2VaRJ3TlUpWDHnkriE8TVBOrGAq7SAgHE6ttIxRGBewaGFDCE42R8

GET {{baseUrl}}/users/me/bookmarks
Authorization: Bearer {{accessToken}}