@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

### Get all thread categories
GET {{baseUrl}}/threads/categories
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDAzOTIxNiwiZXhwIjoxNzQ0MDQwMTE2fQ.EVb9NYc2ut9bQ89YnPFjrtrfn0W8Q-C-dNt8D_3gTn03vk-IDLqRhW7D_blUJPvmE9T3jOOtcseyWcAGG-Wzcc9ZAFskIbsqMqIX4iE3s3mQq1iL5GVkTPOHTvnhRCc8U3BfpMJEoPKSqwgvBs3ILVAUAFed0aBzyVZytWk6fzbp3Qmi3qCMsgvxYPB-MZ24sEWkFx7jRS77r8v0lkhFRFb4z599s2tCHa9cVp8oMbKnZKPXUICqnQ1h9-fkvfn02i3iFyxlWauoHzbV4kiob1M0LAzBBEILFKJckwublkPLmuqg0Li-oslABV9rictEClV_KGIYiRKzYu0CypQH6MaWdCZJGyb-vTaileC_HLKyyWPQaoIzX7tmpNkxeH7a_mTz5Cj_8D75nNfA6O7yxPb3F2x0_sudWy6nYlZJrilkbUXCSfMdJjNpAwvEdX7FneynuK2J0gcqq3liuLqrV5HegcUkUjU1pGNUfZBE_jwLm_XnkWhFeVCfFwRX1gJl3uf2Ngqg4C-QkguvdVdNfPUBcw9Mj3P04DpiQVq_1WCu4cnWHj9knALeYha3tK3tqXsJd5mRJGvDqy-7SysaJvLfLp8bkz8pIH-I8_9wuPXfU_MbetkojHcFjm738kf1PhtcFGVqCdY4xhyuCHTpH2dUWfGPKBsQZYSx2h6yaPA

GET {{baseUrl}}/threads/categories