@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}


POST {{baseUrl}}/threads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzQ0ODY2MDU4LCJleHAiOjE3NDQ4NjY5NTh9.w7z0AByDHbCpEpL8gxKsdds3e2kRgdiUbmVGBoF-Sp0IEsrdLYAcmmYIV0Lp_SFHw0re405SjV7A-g40XzrMdZQnsUZYF3z59xJIRsrjc2VcEpDgmu0xO77JzVsDUbTCyNnSSNws3GbzPFPy31XF-YERWmeDVsCQ9MhU1d7bJVoEdEzXFMkzk1SfVbuV7WC2SFgx7aV3IGozMHVyKmkTL1dNIqjpMIgG3MWwLxkqNhid5bL1MTwUhfbdoGj2WjKHSi3_sBkR4rKDtVBoOP1h03qWwGukk6uG6eBMvJsYkqqp4fMK6CaUNCsM4aEzA_ETtTdMXlBTSD1USYrG6gwoRuHaLqg6FZDqDQ2zTVQ-MEvELXXTOjd5M83JB0pS2LKX3hGCXVcE9BUCxiI70nYscxpV_Iu08aR_Gn9n38tA9Cz1WlPS9Ez3_RchWalxsMDddXWWruxrrc2EOWx-YaIiwsDNdZG6uVTU0W_XSeqalIHvkOL0enAob9mTYB7XaTMwM3TqxbrKuhb6RZwec-sb3Kc81Bvq6CE66NyCb8rRxQOv-yqK7XJoo7BWRDDpZs_QiYjvzJfssgMIRiVKiZ7wh_6l3Nq074-Me407MvS954K4m8B2qbKZIwYOvpxTHiQzvUfRuRe0SEhWWr37yK9MpqOhC6CarhLBQOhoVN0xCnc

{
  "title": "New Discussion Thread",
  "content": "This is the content of my new thread",
  "thumbnail_url": "https://example.com/image.jpg",
  "category_id": 1
}