@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

### Get all thread categories
GET {{baseUrl}}/threads/categories
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjQ5MDk3MCwiZXhwIjoxNzQ2NDkxODcwfQ.ly1BBG7GkeeJ7HEL6U4-vMsjZO4Q7oxtbhhE5xWFyrM7GZzPVBwHrXU1KOKADLQDH6J0qXSjwXZM71C6MH0NP2fz85W6t2JzzDcbcZMdEwkFGNapR7CJYDBKyoGZCNB7dsA91SkIsyu2HCI8ubYsBPK_TUbNiqIwAdm-TSSusrU6GCp_YHee3NgWgX9W0tmWyqeVGTcW2k9nlZIuzB3vamtrbR3PkM29UtyNN2YLTeLkBG7SzKFXIlglBBMD6v-WkVCSeHbC9-0ARAxGZx9-NM5m5g1YHxIFOkGoana5rDMWrhxe_ZaQvTQLT2ci2I4FipHCyGGNJoMyUjbuAuatltir9vofjEFoQU5ljFp7DRkm14MSvvmytAZ__r5YKuyTBse_xY-AHTFiSl1t118NEyMu4VKmfBJklbwLGSn1ZKZdBgRMPcTT6ORD2Z2BtPtVr4yKvicccHVhw0SvCZqOlLz1BRfdakXbbPHaXsrCyYQv4DzBTR7pvfY1Q7TTXBL36kzarV44B5vtL4JORxp-PRJjmv8prDGhr-z-SGHCDNBfti4FMaiuXrjGWEsAomXQw1njEDXpPlxuC8SBTGH0K6z4GypXoeKHONUr9CziGmfysvAPDMASZKYM1XZdNRce5MD7nk4DwiOX9W9BKVZHzjuIteQ_5sHVsbJKYVo7obM

GET {{baseUrl}}/threads/categories