@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}


POST {{baseUrl}}/threads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDA1ODk3NiwiZXhwIjoxNzQ0MDU5ODc2fQ.H0mUPrkg5c6JrjWBm10AZt5OBRm407ULOpm8Ezu5IlV9m7YM9hCedlj4glyQRZ6g0OUThW_JCMB0ltJHJbrqbkWGjXJvxzwHnQ572y5O87Z-GcmI5koXJr8GyGTW-OJxP76dmx1v5C2m3QTuGmgNDinf5f60wMS3_ctuXvbc2t1O68KU8SRJVD1aMPsYTPr6VX4c9f98N7VD_bOvvcF3p1GnSuDq-3_VPFDn-EIERyU4RfvX1NUpr_wejvzNK9a_hrOl8kv_0j0CUZOlfaENKoqRP8mF0oH27wu8bT7xqOcN11lAl5G6_EtzlkQFS9FZ6Oh610KBqmjs-vVCtWKYXs8E-rzLEI-1vg1AKXw8yMHEumQDoptoEHxDNLYCHAYBpzwi_PI6oXLBYWpVyWfFH8YubosIt_1a9VD0s_JYYLaye9fqJXGE12UvhXjp886vnwGXTmsZjNypzhzD7SmBs1esTHC8jCgI-9XHI8UgFDrfLG2noGwN4PyKCQt_UsiYHYpRztLnBrpk6GQzffsLyjUtNdS9RGqH04SLJU97UzCaGmjLOK16kd50gRJSC3en1otPNwddbG-szHve4yFI6nVKflGlrJi3jWRo7JBAR-gVSGklAMIkh34hw0yI_tNtX6D4i6KmtUkBLe236u9dbR4d-eKVZ-ipzTSqGN4BvyI

{
  "title": "New Discussion Thread",
  "content": "This is the content of my new thread",
  "thumbnail_url": "https://example.com/image.jpg",
  "category_id": 2
}