@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

GET {{baseUrl}}/threads?category_id=2
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDE1MDQyNCwiZXhwIjoxNzQ0MTUxMzI0fQ.Ml9PO4cErqOWFmDnxCDborEASxlBdgLWn-F7SbKIa4T4ORhv0bt_8QA1h2vQ3M-VozytDrVQgWgKAZ5tc2jvuIdAXtCpFv0goFStKvTcUugW81bKmBICpulsnebix-Dt-hdPa_p58IIMSQn7NP8Ba1jAeJNtj3jI5_zFbg_MbJSorbk59jhWoDqGzE4zg0EJfnL-7JK1KHVYqrbdrBO6H_00QQxpjQKfNfDCnwj0nVaLQ2D86glEsISTv5kBds6FZqxs5VMsVvldV45BYoxVLiktuoNYHcMWmWa85Et1Xo4KiVcWgCYMFZFuGBkZZW5hl3lUybgUnTE_o3QklvvjrIPXGYrrYioJpdLRUMIWak21TdOOXQ5gd41h8N8EZZlW1HmeD_LJI4yS6lLQa-DE5PYIKLXTncWgJyNnXVJ4IODHvKhocDuCfwyoarCvTsrVtUPWKAbL9vgtO4319i2wJor9fnWHeoiJ0r46zSS9fb6wILJT4kjPo8ZYBu5eI8WaZ2f5Jbvcs6XsbP23M7igqqA5dvx79yQSi24D9ICcegImQd9Q3de_sJ8mV8_G9fmdKoCFbQSOxIJwg21ZT1EZV3RkyySt5_68FWFbdzjR2PSPETc17IQJ3Wfe-I-B-SCvKW0AJSRWWx--CqecXcccU8TKRF6JD1sbPsmhU4zA0tE