@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@authToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0Njc0Nzg4NiwiZXhwIjoxNzQ2NzQ4Nzg2fQ.ABKxwbeLcShcRjgZYBOtMdaaajrvgBDS8Ae-lvO8PucX4v2UsWtnQXOMuwcsvYu5A0n7uQHMCYaiuqDGS-xgQQNcYaL17WcVDN7R3djgr7luON9bfS5L0x91x4U2juYwbVZ5tTnoeH63FoPuPlsOmvIMvHMqLAAclFvJY5vZ5aREfti0OszFl7OisD-IBA8a_0kvbd45zQclb_KmW9eDL-AJvY8EeRnlizN5BTrGqU3HAfpcLtw4p9NY8xPGx1_-bQEMfrXJQaLqvCr1dMcF5eJx1ae4Ry8OecfpbpdDFOKgY0pIYTrdQ5XOwZaqo7KNLX2_pIxoZ5Bbu2nkBw9CfNzOFfZk1m2kum5IWbNi-qZwdKInam0O8PrHYYeZxdirs8qcIPGdgKDHAJArh7fgFG1tQGiu3OFhSb22hB4I6UXQBVY36-0a1TVhTCgQhd8MQimxatg1jaHGH4MPelsH4oy8hI_rlytn_D4KtzUByQGtPMpuIgUZxbgJmuTVOgHKHIhFT-TgZvald6_2EMLvHKbx3kwTs1fBk7PKHiCfFHOauR4uVNipspzE7ZOhO3VjuPKq8U96Am37kuDPsIrgVfttpFrRwb_jiBf88YXFVeFjIxx0wyYXdMo8lcmOJgrDYK6nDiZcs7YgQVaUkAPLkN1r_Do-sheyMc8Qp3Flo2M
@query = مناقشة


GET {{baseUrl}}/threads/search?query={{query}}
Authorization: Bearer {{authToken}}
Accept: application/json
