@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

POST {{baseUrl}}/threads/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjQxNjUzMSwiZXhwIjoxNzQ2NDE3NDMxfQ.J5Uhf9vlxuBQ8gGT5U9LGNpvef9b39qrbg0comjBvx93OGClgGzoyKQ0Ey6p5X2TpX-b_7pFhZ-qBU3hjah3E_NlpQblPd04ATQzatney55l9XDJI1cXrk80okyHqpTsbuSAH4f-YjoQ9-JnDL3_3v32mRiAiRC1fqzZMdZKUt_M0xpI1AXRSTolZbRszUYhZgHBpQM8FTYMcsohdOvrY_leayKSwiykgV-2UUjFHC41JCC8z4KDix_JxWsuX4ppGK5MqrGlorB5bHUCagze_h5eVFLUl4M4-lIA1l96F8cSVIzUnJ5jB9j6jUezO4FVPBcVeak8h9nwVQOsdneUJS6ZFEVG3AgI-9sSuBv_KgvPXY7xQb7gVStMtERu4plPdmFrUIOZdwKhGZfL5EvMh_ixpfNGMBczAcMsiPa4DCmNlCj5tefE37fzfQLyl35sOofpxx61buMgBrla2tJNUfaMa_g1WeU5OWM8g7t48qIpEspvb-Ecz1qZmTSs9u9lrJUvPWUQSTfgP8-OIStrBFnNxztCgySb8Atn3jCWprYkjgqEIbytCxMioBOFz4lFh_CCsGbc13qbq925nKkO4ujXGM8tf7ebUKwtYvRJTp7T-rBcY0440oTV_Un4428iZ7inXggvE87Lj1ubhmjKcWT_TcAH9FQC-t7iHbZZgF8

{
  "content": "This is a comment on the thread"
}