@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@authToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjQ2Njk2MSwiZXhwIjoxNzQ2NDY3ODYxfQ.BMw2uE8ANWB8aQQu94RVNICL3mSpYZESpoJnAmRstHHCJUklFJGNcSAEmaAKnslRTHpWIdL_hta5zLSHG-vH4xrBjshXA8pUA-4pYMC1jqB5TvWjUm-jQPTOwzbMPHKdrhiN9C_dJ9fvjbWs2aNS_KbxcDC76wm6ynu1BStleI6LAb3-Sf7ukwRzhm5yNrgSywZBxhLjDKw1Zog0GSK1B4s000TzcFguZ3Zh9N75dxFM78TzBKn6fBmVdrmE1jLP_SQz-voGke-Kd_SNedUwvsTqFx6vhFPQJmyOur_6jylWHuJsJ-OV1ANBknRla_1TJdFJb2TlOHFRgeVCheq0TD6NwP87EER1G647vglFRRCNEZjn9xvxORSFgoken1qVRRIETjJ4XYP7gwEtaHBuhpK22H0L20GGxkOR7PKCtvheHWs4cCtTzQRqi2p2w8zf2a-3iDbkuaO-BUbGKChLjUWyaunYkbi7Wn-XYkiHP6iKeiUqAP2HRDaLEbIPlhaFZp-MKa3EeaalFyzezVQooUwsFyac6jtPrdbqXuGs4U2iT6sKowbOe7uFM8Cp4mF9QZ1l9p4vsq7CrKzFodX7yA5X9vKO0_6AGDMKkaYcatIbhwXQA3FlqUbfuJEhyvtl3WykgZxut98E1eNMhO0Gn4CYcc5LQsF9Uz9bcuBpgqE
@threadId = 1

### Get thread with default parameters
GET {{baseUrl}}/threads/{{threadId}}
Authorization: Bearer {{authToken}}
Accept: application/json


### Get thread without comments
GET {{baseUrl}}/threads/{{threadId}}?includeComments=false
Authorization: Bearer {{authToken}}
Accept: application/json

### Get thread with paginated comments (page 2, 5 per page)
GET {{baseUrl}}/threads/{{threadId}}?commentsPage=2&commentsLimit=5
Authorization: Bearer {{authToken}}
Accept: application/json

### Get thread without votes
GET {{baseU
rl}}/threads/{{threadId}}?includeVotes=false
Authorization: Bearer {{authToken}}
Accept: application/json

### Get thread with minimal data (no comments or votes)
GET {{baseUrl}}/threads/{{threadId}}?includeComments=false&includeVotes=false
Authorization: Bearer {{authToken}}
Accept: application/json

### Get non-existent thread (should return 404)
GET {{baseUrl}}/threads/999999
Authorization: Bearer {{authToken}}
Accept: application/json
