@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

### Get all thread categories
GET {{baseUrl}}/threads/categories
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDAxNTgzMywiZXhwIjoxNzQ0MDE2NzMzfQ.jCVdKsmS94ZnO2C0aFm-sTZC8YwEcj-aByXy2c9Y_q6BAzypdznD72iB5jliuxgtdwvS3ZT7Qfqu7WNXOERlaAPhabzer7i72EFnxa6ZIkHslJsGVeMd_uWqW2xXWL7Zjw7ZktIettXyHuJWUIKrMedAbt-9Q9LYVoOVsLV8LyAj9JvNA0PLlmJUFAw8sH2QpdX9iFwbZQE-TGCM_cOC6ul-HPN1AYw9mmQlvqI5kGgs-SlKbdBkCDx9gTlOki2c59MDoemZYOQEjix35HnHzwqe2u2eX7syJ11Eyk_26OXLhiJwHKRhh0e9D3iPBVTVoyaDTJ15_UQ5K78jgG7VbsUi3PqowknbhYBHV22kmG4XekxswrZe2gVrjJBljFtlthtyMDJ8XEVpYWZRQLKD5zLbMHM-fmEr2aBoeSTpfk7pBm7q5yyJLe5aHwGKwz0IiQ3c6vSnPgjtVsDIMxxtvegDKybIOJdATEArwAsGv0xqZKGvPE5mjBljwGgHCVOCrREYrXMu8aydAupnwX8KWB7rDtSzS8RDrNAuXVuPhzWEXeLX_DSgwLv9YcXjRAP4yQkDrk4H9csK6PCjR_LbJL_8CcfEbZOxaoOg3421JVJHNwgR3im1hZKGnEnrumNnss9XW2VN6BJI2N72_s5SuYtsiGvbZbhtJpViUubhwOg

### Get all thread categories (unauthorized, should failed)
GET {{baseUrl}}/threads/categories