@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@authToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NjgwMDIzMiwiZXhwIjoxNzQ2ODAxMTMyfQ.nDGlvkFjf4R3tTrcrEOVxS-uf5MMI_8nn2K3FIRAeoc4S2a45cI2_KeTeBOqWLuxTXdbZZkXiBjh81lvKlwguHWZLiGX7uu0MY2agHcbAnS5J4hXodlkI9kM0GicrO4o2mRPNcpGCGOC0xonyvJxNtM7MNhV9KsJ4lgK7ixi72FUVMOwlXZ7fSbVdG3KizmpoUhJOvGSKJG-RZ8Bzl542nYzv0-_eqCKkIjXnoqKnu2NoGAD6uMoQA5bp_HGBD0x3FCWyigX5Dh8z_RKIvEQXCbSBMXx064X-sCi-BwZbrNtmdKfX0GGxfyK_y0djmQiEjr5ralc2koXOtfHnsHwrSQjt1q3ULVZeVJexELU_wJm7ouf-OKSCvtUqGqQ2i6TmIu5f6lhA5NT7Un69vFxIXV0dw7pFOjdLXdWeR8q0syiqADPd2evn668Y2bj5PmcW5SiQTxvHkgi4Y5LjRIkRCY98C8QQ3ssQ0ock2Ipe2xwkFLFy6G137Ic_smOfSq9LI0RqydOAN-wmYQ3RXN-xLwEUQl38QpwTWeAgCe55qy_eDT-w-UR0wPpYv9AuMYIUdxhUa9Zl_4vstqtQUaiNrGlv0KbHibzaT7grYJkPIEXtvQ-OWZ_e52ecmle0T-kp1qoEEsFXJsG_3D4SyWJEcYfXolh6IpqKVxFptIFa9A
@query = مناقشة جديدة


GET {{baseUrl}}/threads/search?query={{query}}
Authorization: Bearer {{authToken}}
Accept: application/json
