@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NDM3MzY2MzUsImV4cCI6MTc0MzczNzUzNX0.L4Lgsy_8e5j3YP8OZ-peKLblzFWDDssW2jVRRVycGVNR5CuI1N6d8xm06LNFB9tG1wnn79SGxoAK-2kKWZbXoBXXnpiddRjyddw-ANoq57GcN8Tk_EzyqaRaoKDTxi4cm9nVMroBryvq0a3enRvXlxK7ZnwmjsfzUcb6_9qxiJ1V7NBDj2pU8YNf3Si_PVIGAdsPyuXzUq_Y-b5ijY82g3Xjs1tdVTN9lJYCsGEN50xuAdmDMIzYpsgyEaOFxpJ3c37gDwF0_QOKWYKkQF2MhMPaCoO0nggeOFsqeyCmFPBQknbgpFaQ43oBDwF2x2-VZXOSP8HXaKGpeiJW60BWjufCDR9oiqAKC4jQdJYghSW-hGMm_BsZ3ez2nPsSizkD4M5_IdKAwiY-fNk1UTw5UBqju9r9VYWJNL-4wtJ7K8Bj1_UqZ0Hs3luoMsmJ0HeA32txDivY4tXQlL4lMfIPvp2L6f_d_RA5swrpjT9UF5cUi_0YjRjZKamSFd7aHnCMxBl1owaqb1OhuKklQgiJh7Qd_qHsq3FO286skfN5Cb-5uG5fXp8HyZDLCe7kgnVgxWNQtCsOfafbzdx098vpDvZ6ziuCP6edVMhyIiiHp4ZDFgguOj2s7Cw8W1YORCwcVOMSBprlkJ9KxYgGw5uXyYQD28KnqE67Zw3LERZGCew

POST {{baseUrl}}/threads/3/bookmark
Authorization: Bearer {{accessToken}}