@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

GET {{baseUrl}}/threads?category_id=1&search=مناقشة جديدة
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0Njg4NTU1MywiZXhwIjoxNzQ2ODg2NDUzfQ.BD2jMiFW5cjXJZMYNQhcDGd1vBJ1INd1Cbm2FqWGQPAjYJPv6h4QVdgyP0oEqQId7QTpzs2l013DBQX1IuFkbSL4znuISqAsnQ5CHjUGUT21QPEYEVBODkUgh8gXy9rYDjRV94iGnc6Ti4kYGMi64od4o4usjMQC8zyMsCdHu89W-1PvvbuWbUuIn-Akv3CkUrgF5IHW0GpnqzpFp4FnKBNtazEwGNM4JfRNl0S5QIcSe10GyuAJdWIF4g1UHo_AyCpOyQjPryHDVexLJEu4gjDEjSNJpE7qU0Kpg4RJC28HOkSkR8O-uo-pxLTYe0cApuEGOrXFUwhUkR2xNHyyHIBMMs__WnBkT7CwP6-SP3rI4TWM3NQIxuHz3FAUsxCtpxC8EASYNDzh2ZLwIRdRFBQKikMP9f7mrCvUjlROUbA0a_ClbtF3euJlxIHOQ-5piAfZx9i9wSSLSa6xr3IEpcgVvTV7UGYZyaSAGwqYw14lDy8HE1b1kHAXb_nQ7UsrwnyPiGJpjp3pj1VlC-3DMTHT1iX9zqI6khxOkOOQl-PrnD_6O-tPSsTGJ5Byb1w0xRlC_Q7J9weMn0KBIR_O3Ms-2cGp6OJasjsFdUncWnhKCI_8N_Tn7LjLVJ7iheVTNUCOJBWj-3lDZmQ_a51aJih3EyH1X1MB_IMiwgqLNqI