@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}

DELETE {{baseUrl}}/threads/1
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NDM2MTE2OTgsImV4cCI6MTc0MzYxMjU5OH0.hmkk6v8UTd53_dOcEzLntE3k3R3Rz7wLxtqszpiB4QvL1nBUXO9Ce_NaS6kdmZcR2MPbbnCU--EBpUE1UJn0ac2jd9dHeF8c4-DzC7JGZ4fHUkYAZDlMq9cfzytZUNihSkxXRwZp2TANp0Lk1n6LmkprVc78fyuvKRdc02EPLT9p_kfQyMi14GTxKUnP2aYXhUtbbXvdy5WFPepy4g-OyUcNZpKziVxf-ztdy45181C2XpvDAusky5k2skMQT-LrlPZ51WWnNHVZ-dGDq8-yhXE8ny-4WPgHcN7IyvyAmP4WeURpXaSi4T8fLizQK0x8X-ECxz-qcm9WxSW0-jCypCvxVI44EO6Xn_RM1n0A0uiO1QrOhotPUiYl1LTtO7kubBAk-_9ECT6jkd9N0Hp2De5hjAeR5Ju0GN-EIWbEbJCnxI_aOlw1sfxbY6JYI1gK7Wsl4m__QP9hJ4E0qksnn7SAD4GPobWPn3i9Ri0s12LbrBVkCqwQOp7HZhnekVfXDdJibES3VBPuMnxWCgutXAh8xGYQETAfZLgLSlhrWMfRKNZb1WFJ1r005cdBCRgSyM20tN89GX6ggbB2xV8utzW8C7qn7IJ1LWn1Y6G2tFd-6FR-zDkGmVL06hYIKwNGDnG5BKPNK1Ojii95ibuJ1Br7tICv-yRUK_xysnw80OM