@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@studentId = 1
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDA1NjcwNywiZXhwIjoxNzQ0MDU3NjA3fQ.f_onWQK6kxCeiu4ouM861YYGH1nJ4ndiY_mqF8uH4FXf0-Y8wRPW9Lkm_w-sIlt1C2wJw20oKzeoj6IDK_5WdDGkzFUOeaSziJp_2ad6Qe0ncxCDGzxd-aSN4phgzBkEoZHVCS6MjfEEC_NvHDwNbnIeAqv2jPvuPcbuQN7jxnVJZk4Lsnvvy3CQKF9DKSaby9a9W-K-kDm8l9UM3-hNZ7VRGJ9jQ1EV7BXoVI2F1l14sYH6X02ew-a_b8rumPAGbHOKW3M1kfqADrmZIQtuT-E2hmEIXSCh_fFlxqPKacQgDwtXC-wD-K9D8z00a03Gc69SCuQUClFoIeyogQjG96zX1aHpJwzzbYK8l7sGH2U7iy5_IpHiLLNyggbBijHfsk0KQiqoOVxLG0XZCaAoh2eFpF6UQPpOK_DesiagPc-jMGJ70F2OHZ-YXS_30olUSBIkaM4tUroAc4feF8xzFWJ_fEelSGWKngfAYU8awoGUcAzxv8qa33qiVDcd_GNGDe3zrJcFGvQqG9nPGNsqr0uXuTDMuvVDS1DoSCpqUp-TPitDvffNSMYekJol7mbls15Tob9We-ZgP1tw_vyPK26q7grNbSRF0no5NVcyYZFpImXaXQi0FoCYPB6zKPRclaKnq8CV4zu1Z5JDaPYq-NRKi_rTCKj8wRrNyccETaY

### Approve Student
PATCH {{baseUrl}}/admin/students/{{studentId}}/approve
Authorization: Bearer {{accessToken}}
Content-Type: application/json
