@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken = eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDAzNjQzMywiZXhwIjoxNzQ0MDM3MzMzfQ.aqSF34szo41vlKcuQKPMH2shmR-3Ny2DIuit3dwqTMYkFmCbHnt5WNpxwQVOSzQoJYZdWzcFpSf-wTUhWR2P10TcL5UGtH6elKuIPg7Ylk-8UDLFMDUka1yU_h_YgjotqmvMY9ONqZpUPrd2bFlSp2d3pkA9U-lKQU7fEGFNm0yree2MC88AoaHoiry6vWs3JHFK9j-tIVjd_AH-6MK8wq03zvwnN_qVjHYBT1J26Um4FcY0kJ3mVYKz-LTl2pl_FpjT_CdzU0skO9eYsAbQa30V-3QpWgRROhBByPhIK5n1-MmK2G_XIR7s3nBtpWX0CoBwaz4EGsEFxTblZ-m6zdGVBSIkBSkAAY8saYhaEkp_sCvfGmiBta19ZkAYC_Pj0OxzDcz1jtgWuZWQTe61rHcR5XrwAqBT17js72M8aS9EDsZfJ0Dfipu_xybJP7-jb-_jLrS2HxnebjnXpksK0Nx1EKXFPAlMcIuMvfklHVLW6qtdC0gI_s8cGybPp8N01zivdoWExqGOdgyZp3Z-GR3f4o7AsdMvik2UTze9Ws1XpqmdXx9f8FYS1qry1cXel4tnO4pVB7NdI3J5r4OLHcycg8q1cr1T08FPmIcKvo2sNNG3JOU5szxQ3-c6wDbOGawyFbN7sJAETfdz4OP1Gz-mv5CQpt9nNJ9ZR18ZPmU

GET {{baseUrl}}/admins/users/students?status=PENDING
Authorization: Bearer {{accessToken}}
Content-Type: application/json