@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@studentId = 1
@accessToken = 

### Approve Student
PATCH {{baseUrl}}/admin/students/{{studentId}}/approve
Authorization: Bearer {{accessToken}}
Content-Type: application/json
