@port = {{$dotenv API_PORT}}
@baseUrl = http://localhost:{{port}}
@accessToken =  eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInRva2VuVHlwZSI6ImFjY2VzcyIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc0NDA0NjEzOCwiZXhwIjoxNzQ0MDQ3MDM4fQ.XjoHXJYueYPxIEvIQKS1Dy8zXMEVeLIapwM35QLe2ossS0CrZq143r_1ZY1jRiIBSNdX03I-liUszaIIHuepaSKaGn5pcM4Bagrzb1Jmk4G8XSY8b-kCIgJRRL0QwM13bw_sszwEG4mzdJtvcb_8H6aO1vE2Pzgd60YwgKGMadpKvGhwZM43HalHToi1Vwf0m_UtyxCOH6V923B5IYHtLh84026VE-hpG4HIzbfegZ_p0tgB1r-E5SNc_RjJ6GHTACS3nCI9Icc4ifZMUiqtCE1ksxCIZs-wUnlQeDLmUEgBMCA-ccPPInd4uvCPeMZ5u9563IgXys9oUdKAYgD_o5kTIo79SvkjqErSGo0jtB6MpIUj-sutHK3igXvT3WleO6DDW1lSHep6FrzYE77d8FzA-W8c-lBOK2dud-ycOHnixM0Nh2qzT6Oj-mDlGELp2ctTMhWGz_XVX73_bHCvMjvdSLEDV4N-0eQXKxjYIohozO6RSZFwwgOrIqThYoABxYvJnbKvGJsIFuR5jIminlP1HmNJSnNwfYsECN4zw71otaW-qz4NByMjFZ7_vpxqBADUQwpqP-CakzmY0jSN69STTvCqSEWLdVZhaoLAekJazCNzcDSwC-rBkd_y_o15T-FNY6XIAoZBU9YDv_TAHambzfzb6_VycyhmvBtepWs

@updatedCategoryName = Updated Category 
@categoryName = Test Category 5
@categoryId = 4  

### Create Category
POST {{baseUrl}}/admin/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{categoryName}}"
}

### Delete Category
DELETE {{baseUrl}}/admin/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}

### Update Category
PATCH {{baseUrl}}/admin/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{updatedCategoryName}}"
}